<a href="https://colab.research.google.com/github/surabhipandey18/FoodAgri/blob/main/cropyield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from  sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, confusion_matrix, accuracy_score

In [5]:
df = pd.read_csv('crop_yield.csv')
df.head()

Crop  Crop_Year       Season  State     Area  Production  \
0      Arecanut       1997  Whole Year   Assam  73814.0       56708   
1     Arhar/Tur       1997  Kharif       Assam   6637.0        4685   
2   Castor seed       1997  Kharif       Assam    796.0          22   
3      Coconut        1997  Whole Year   Assam  19656.0   126905000   
4  Cotton(lint)       1997  Kharif       Assam   1739.0         794   

   Annual_Rainfall  Fertilizer  Pesticide        Yield  
0           2051.4  7024878.38   22882.34     0.796087  
1           2051.4   631643.29    2057.47     0.710435  
2           2051.4    75755.32     246.76     0.238333  
3           2051.4  1870661.52    6093.36  5238.051739  
4           2051.4   165500.63     539.09     0.420909

In [6]:
df.columns

Index(['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='object')

In [7]:
df_final = df.drop('Crop_Year', axis=1, inplace=False)
df_final.head()

Crop       Season  State     Area  Production  Annual_Rainfall  \
0      Arecanut  Whole Year   Assam  73814.0       56708           2051.4   
1     Arhar/Tur  Kharif       Assam   6637.0        4685           2051.4   
2   Castor seed  Kharif       Assam    796.0          22           2051.4   
3      Coconut   Whole Year   Assam  19656.0   126905000           2051.4   
4  Cotton(lint)  Kharif       Assam   1739.0         794           2051.4   

   Fertilizer  Pesticide        Yield  
0  7024878.38   22882.34     0.796087  
1   631643.29    2057.47     0.710435  
2    75755.32     246.76     0.238333  
3  1870661.52    6093.36  5238.051739  
4   165500.63     539.09     0.420909

In [8]:
print(df_final['Crop'].unique())

['Arecanut' 'Arhar/Tur' 'Castor seed' 'Coconut ' 'Cotton(lint)'
 'Dry chillies' 'Gram' 'Jute' 'Linseed' 'Maize' 'Mesta' 'Niger seed'
 'Onion' 'Other  Rabi pulses' 'Potato' 'Rapeseed &Mustard' 'Rice'
 'Sesamum' 'Small millets' 'Sugarcane' 'Sweet potato' 'Tapioca' 'Tobacco'
 'Turmeric' 'Wheat' 'Bajra' 'Black pepper' 'Cardamom' 'Coriander' 'Garlic'
 'Ginger' 'Groundnut' 'Horse-gram' 'Jowar' 'Ragi' 'Cashewnut' 'Banana'
 'Soyabean' 'Barley' 'Khesari' 'Masoor' 'Moong(Green Gram)'
 'Other Kharif pulses' 'Safflower' 'Sannhamp' 'Sunflower' 'Urad'
 'Peas & beans (Pulses)' 'other oilseeds' 'Other Cereals' 'Cowpea(Lobia)'
 'Oilseeds total' 'Guar seed' 'Other Summer Pulses' 'Moth']


In [9]:
df_final.head()

Crop       Season  State     Area  Production  Annual_Rainfall  \
0      Arecanut  Whole Year   Assam  73814.0       56708           2051.4   
1     Arhar/Tur  Kharif       Assam   6637.0        4685           2051.4   
2   Castor seed  Kharif       Assam    796.0          22           2051.4   
3      Coconut   Whole Year   Assam  19656.0   126905000           2051.4   
4  Cotton(lint)  Kharif       Assam   1739.0         794           2051.4   

   Fertilizer  Pesticide        Yield  
0  7024878.38   22882.34     0.796087  
1   631643.29    2057.47     0.710435  
2    75755.32     246.76     0.238333  
3  1870661.52    6093.36  5238.051739  
4   165500.63     539.09     0.420909

In [10]:
encode = LabelEncoder()
df_final['Crop'] = encode.fit_transform(df_final['Crop'])
df_final['Season'] = encode.fit_transform(df_final['Season'])
df_final['State'] = encode.fit_transform(df_final['State'])
df_final.head()

Crop  Season  State     Area  Production  Annual_Rainfall  Fertilizer  \
0     0       4      2  73814.0       56708           2051.4  7024878.38   
1     1       1      2   6637.0        4685           2051.4   631643.29   
2     8       1      2    796.0          22           2051.4    75755.32   
3     9       4      2  19656.0   126905000           2051.4  1870661.52   
4    11       1      2   1739.0         794           2051.4   165500.63   

   Pesticide        Yield  
0   22882.34     0.796087  
1    2057.47     0.710435  
2     246.76     0.238333  
3    6093.36  5238.051739  
4     539.09     0.420909

In [11]:
X = df_final.drop(columns=['Yield'], axis=1)
y = df_final['Yield']
X.head()

Crop  Season  State     Area  Production  Annual_Rainfall  Fertilizer  \
0     0       4      2  73814.0       56708           2051.4  7024878.38   
1     1       1      2   6637.0        4685           2051.4   631643.29   
2     8       1      2    796.0          22           2051.4    75755.32   
3     9       4      2  19656.0   126905000           2051.4  1870661.52   
4    11       1      2   1739.0         794           2051.4   165500.63   

   Pesticide  
0   22882.34  
1    2057.47  
2     246.76  
3    6093.36  
4     539.09

In [12]:
y.head()

0       0.796087
1       0.710435
2       0.238333
3    5238.051739
4       0.420909
Name: Yield, dtype: float64

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
model = SVR()
model.fit(X_train, y_train)

SVR()

In [15]:
predict = model.predict(X_test)
predict

array([1.00154442, 1.00086333, 1.00999501, ..., 1.00391631, 0.99063237,
       0.97245255])

In [16]:
r2_score(y_test, predict)

-0.0012273308940282668

In [20]:
#Randome forest
model2 = RandomForestRegressor(n_estimators=100, random_state=42)
model2.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [21]:
predict_rf = model2.predict(X_test)
predict_rf

array([4.840495  , 1.21322027, 6.57619109, ..., 1.98146528, 0.63201646,
       0.3405306 ])

In [22]:
r2_score(y_test, predict_rf)

0.9040558184961285

In [23]:
from sklearn.ensemble import GradientBoostingRegressor
model_gb = GradientBoostingRegressor(n_estimators=100, random_state=42)
model_gb.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [24]:
predict_gb = model_gb.predict(X_test)
predict_gb

array([2.3983703 , 2.47426308, 6.39304913, ..., 6.66097982, 5.52323689,
       2.13917032])

In [25]:
r2_score(y_test, predict_gb)

0.9030806810446764

In [32]:
import joblib

# Assuming model2 is your trained RandomForestRegressor model
# Save the model to a file
joblib.dump(model2, 'crop_yield.pkl')

print("Random forest model saved successfully as 'random_forest_model.pkl'")


Random forest model saved successfully as 'random_forest_model.pkl'
